version: '3.7'

services:
  gitlab-web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-web
    hostname: ${GITLAB_HOST}
    volumes:
      - ${GITLAB_CONFIG}:/etc/gitlab
      - ${GITLAB_LOGS}:/var/log/gitlab
      - ${GITLAB_DATA}:/var/opt/gitlab
    environment:
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    #environment:
    #GITLAB_OMNIBUS_CONFIG: |
    #    gitlab_rails['gitlab_shell_ssh_port'] = 2222
    #    registry_external_url 'http://localhost:4567'
    #    registry['enable'] = true
    #    unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:
      - gitlab-network

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
      - ${GITLAB_RUNNER_CONFIG}:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network

  gitlab-proxy:
    image: nginx:1.11
    container_name: gitlab-proxy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${CERTS}:/etc/nginx/certs
      - ${GITLAB_SITE}:/etc/nginx/conf.d/gitlab-web.conf
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network
